version: "3.1"

language: vi

pipeline:
- name: WhitespaceTokenizer
  intent_tokenization_flag: false
  token_pattern: None
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer          # word-level
- name: CountVectorsFeaturizer          # char-level
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  entity_recognition: true
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.35
  ambiguity_threshold: 0.05

policies:
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "utter_nlu_fallback"
  enable_fallback_prediction: true
- name: MemoizationPolicy
  max_history: 5
- name: TEDPolicy
  max_history: 5
  epochs: 50
assistant_id: 20251113-175501-one-packet
